"""Domain models for the PR review agent."""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field


class ReviewSeverity(StrEnum):
    CRITICAL = "critical"
    WARNING = "warning"
    SUGGESTION = "suggestion"
    NITPICK = "nitpick"


class ReviewCategory(StrEnum):
    BUG_RISK = "bug_risk"
    SECURITY = "security"
    PERFORMANCE = "performance"
    MAINTAINABILITY = "maintainability"
    ERROR_HANDLING = "error_handling"
    BEST_PRACTICE = "best_practice"
    LOGIC = "logic"
    CONCURRENCY = "concurrency"
    RESOURCE_MANAGEMENT = "resource_management"
    LOGGING = "logging"


class FileDiff(BaseModel):
    """A single file's diff within a PR."""

    filename: str
    status: str  # added, modified, removed, renamed
    additions: int = 0
    deletions: int = 0
    patch: str = ""
    previous_filename: str | None = None
    language: str = ""
    token_count: int = 0


class ReviewComment(BaseModel):
    """A single inline review comment to post on the PR."""

    path: str
    line: int
    side: str = "RIGHT"
    body: str
    severity: ReviewSeverity = ReviewSeverity.SUGGESTION
    category: ReviewCategory = ReviewCategory.BEST_PRACTICE


class PRSummary(BaseModel):
    """Structured PR summary generated by the AI."""

    purpose: str
    changes: list[str]
    key_files: list[str] = Field(default_factory=list)
    risk_areas: list[str] = Field(default_factory=list)
    test_coverage_note: str = ""


class ReviewResult(BaseModel):
    """Complete output of the review pipeline for a single PR."""

    pr_number: int
    repo: str
    head_sha: str
    summary: PRSummary
    comments: list[ReviewComment] = Field(default_factory=list)
    skipped_files: list[str] = Field(default_factory=list)
    files_reviewed: int = 0
    duration_seconds: float = 0.0
    model_used: str = ""
